<a href="https://colab.research.google.com/github/Joel-Wang-Math/MIDAS-AI-for-Engineers/blob/main/Copy_of_day04_part2b_abstracts_validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Day 4, Part 2b: Featurizing Text with an LLM Pipeline

**MIDAS Summer Academy**

In Part 2a you used the Groq API interactively. Now we'll make a _pipeline_ for making many API calls programmatically, in order to process a volume of data. We'll be **featurizing** some paper abstracts--extracting structured information from unstructured texts.  The abstracts are open-access papers from behavioral and health psychology.

## Setup

We'll setup our Groq calls similar to in the previous notebook. Note that we'll be using the parameter `temperature=0` to make the output as reproducible as possible.

In [1]:
!pip install -q groq pandas

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.7/143.7 kB 3.7 MB/s eta 0:00:00

In [2]:
from getpass import getpass
from groq import Groq
import json, os, textwrap, time
import pandas as pd

client = Groq(api_key=getpass("midas-academy"))
MODEL = "llama-3.3-70b-versatile"
print("Client ready.")

Paste your Groq API key: ··········
Client ready.

## 1. Extracting features from abstracts

Imagine that we want to better understand patterns in the published literature, and we want to extract the following information from a large number of paper abstracts:

| Feature | Definition |
|---|---|
| `sample_size` | how many participants are in a study |
| `population` | target characteristics of the study sample |
| `method` | does the method involve an experiment, testing associations, or something else? |
| `includes_causal_claim` | does the abstract use language that implies one variable causes or changes another? |

## 2. Load the corpus
The corpus (set of text data) contains 30 abstracts; we will start with 5 of them.

In [3]:
DATA_URL = "https://raw.githubusercontent.com/elleobrien/MIDAS_summer_academy_student/main/day04/real_abstracts"

def load_corpus(name):
    local = f"real_abstracts/{name}"
    return pd.read_csv(local if os.path.exists(local) else f"{DATA_URL}/{name}")

abstracts = load_corpus("abstracts.csv")

SELECTED = ["ABS-001", "ABS-002", "ABS-005", "ABS-006", "ABS-023"]
subset = abstracts[abstracts["abstract_id"].isin(SELECTED)].reset_index(drop=True)
print(f"Corpus: {len(abstracts)} abstracts. Working subset: {len(subset)}.")

Corpus: 30 abstracts. Working subset: 5.

## 3. Our first attempt at featurizing
Let's see what happens when we pass in a simple prompt with a single abstract, as a test.

In [5]:
example = subset.set_index("abstract_id").loc["ABS-002", "abstract"]

question = (
    "What is the sample size, population, and method of this study, "
    "and does it conclude that one thing causes another?\n\n" + example
)
resp = client.chat.completions.create(
    model=MODEL,
    temperature=0,
    messages=[{"role": "user", "content": question}],
)
# Wrap each line separately so the model's own line breaks are kept
for line in resp.choices[0].message.content.splitlines():
    print(textwrap.fill(line, width=100))

Here's the information you requested:

1. **Sample size**: The sample size is 188 participants.
2. **Population**: The population is not explicitly stated, but it appears to be a general
population of individuals who can participate in nature-based interventions and mindfulness
exercises. The demographics of the participants (e.g., age, sex, socioeconomic status) are not
provided.
3. **Method**: The study used an experimental design with four conditions: nature therapy, nature
only, mindfulness only, and a control condition. Participants were randomly assigned to one of these
conditions.

As for whether the study concludes that one thing causes another, the answer is not explicitly
stated. The study finds a significant association between the combination of nature and mindfulness
and improved positive mood, but it does not claim to have established a causal relationship between
the two. The language used is correlational, suggesting that the combination of nature and
mindfulness is "associated with" or "has an impact on" positive mood, rather than causing it. To
establish causality, the study would need to demonstrate that the combination of nature and
mindfulness is the direct cause of the improvement in positive mood, rather than just being
correlated with it.

Suppose you need to run 500 abstracts and put the results in a table, one row per abstract. What is the problem with this output?

We can make two changes to how we call the model to help:

1. Ask for JSON with named keys in the prompt.
2. Turn on JSON mode (`response_format={"type": "json_object"}`), which constrains the API to return valid JSON. Without it, models often wrap JSON in markdown code fences or add a preamble, either of which breaks `json.loads`.

## 4. The simplest possible prompt

Version 1 names the keys and the allowed values, and nothing else.

In [6]:
PROMPT_V1 = """Extract the following features from this research abstract.
Return a JSON object with exactly these keys:

- "sample_size": the number of participants
- "population": who the participants were
- "method": "experimental", "correlational", or "other"
- "includes_causal_claim": true or false

Abstract:
{abstract}"""

def extract(abstract_text, prompt_template):
    resp = client.chat.completions.create(
        model=MODEL,
        temperature=0,
        response_format={"type": "json_object"},
        messages=[{"role": "user", "content": prompt_template.format(abstract=abstract_text)}],
    )
    return json.loads(resp.choices[0].message.content)

In [7]:
result = extract(example, PROMPT_V1)
result

{'sample_size': 188,
 'population': 'participants',
 'method': 'experimental',
 'includes_causal_claim': True}

### Exercise: code one abstract yourself

Before running the batch, code the first abstract in the subset by hand. Read ABS-001 and fill in `my_codes` with your own values, then compare with the person next to you.

In [8]:
print(textwrap.fill(subset.set_index("abstract_id").loc["ABS-001", "abstract"], width=100))

my_codes = {
    "sample_size": None,
    "population": None,
    "method": None,
    "includes_causal_claim": None,
}

Background and Objectives : Migraine is a common neurological condition that can affect daily life
and well-being. Lifestyle factors such as physical activity, sleep, diet, and stress are often
discussed in relation to migraine, but their role is not always consistent. This study aimed to
examine how selected lifestyle factors are related to migraine frequency and intensity in adults,
with a focus on physical activity and dietary habits. Materials and Methods : A cross-sectional
study was conducted among 300 adults recruited through an online migraine-focused community from 1
January to 28 February 2026. Participants completed a questionnaire addressing migraine history,
frequency and duration of attacks, pain intensity, physical activity, sleep duration, perceived
stress, and dietary habits. Associations were assessed using Spearman correlation and multiple
linear regression analyses. Results : Most participants were female (88%), and 48% reported
physician-diagnosed migraine. Mean migraine intensity was 7.44 ± 1.72. Migraine intensity was
positively correlated with migraine frequency (rs = 0.31, p p p p p p p = 0.005), perceived stress
(β = 0.23, p = 0.006), and aura (β = -0.19, p = 0.033) were significant predictors of migraine
intensity. Physical activity was not significantly associated with migraine intensity or frequency.
Conclusions : Migraine intensity was most consistently related to perceived stress and migraine
frequency, whereas migraine frequency was associated with dietary factors and BMI. Physical activity
was not associated with migraine outcomes. These findings suggest that lifestyle factors are related
to migraine characteristics, although the cross-sectional design does not allow conclusions about
causality.

## 5. Run the batch

One call per abstract. The pause between calls stays under the free-tier rate limit.

In [9]:
def run_batch(prompt_template, data):
    records = []
    for row in data.itertuples():
        result = extract(row.abstract, prompt_template)
        result["abstract_id"] = row.abstract_id
        records.append(result)
        print(f"{row.abstract_id} done")
        time.sleep(1)
    cols = ["sample_size", "population", "method", "includes_causal_claim"]
    # reindex instead of [cols]: a key the model failed to return shows up as NaN
    # rather than crashing the run
    return pd.DataFrame(records).set_index("abstract_id").reindex(columns=cols)

df_v1 = run_batch(PROMPT_V1, subset)
df_v1

ABS-001 done
ABS-002 done
ABS-005 done
ABS-006 done
ABS-023 done

,sample_size,population,method,includes_causal_claim
abstract_id,,,,
ABS-001,300,adults with migraine,correlational,False
ABS-002,188,participants,experimental,True
ABS-005,98,university students,experimental,True
ABS-006,570,university students at the Faculty of Sports S...,correlational,False
ABS-023,700,adolescents,correlational,True

## 6. Is the output any good?

Every row is filled in and every value has the right type. That does not tell us whether the values are correct.

The most direct check is to read the outputs next to the inputs; Hamel Husain's [evals FAQ](https://hamel.dev/blog/posts/evals-faq/) calls this error analysis and treats it as the first step in evaluating any LLM pipeline. The cell below prints each abstract with the row the model produced. Start with ABS-001: does the model's row match your `my_codes`? Then read the other four and mark which values you agree with.

In [11]:
for row in subset.itertuples():
    print("=" * 100)
    print(row.abstract_id)
    print(textwrap.fill(row.abstract, width=100))
    print()
    print(textwrap.fill(f"MODEL SAYS: {df_v1.loc[row.abstract_id].to_dict()}", width=100))
    print()

====================================================================================================
ABS-001
Background and Objectives : Migraine is a common neurological condition that can affect daily life
and well-being. Lifestyle factors such as physical activity, sleep, diet, and stress are often
discussed in relation to migraine, but their role is not always consistent. This study aimed to
examine how selected lifestyle factors are related to migraine frequency and intensity in adults,
with a focus on physical activity and dietary habits. Materials and Methods : A cross-sectional
study was conducted among 300 adults recruited through an online migraine-focused community from 1
January to 28 February 2026. Participants completed a questionnaire addressing migraine history,
frequency and duration of attacks, pain intensity, physical activity, sleep duration, perceived
stress, and dietary habits. Associations were assessed using Spearman correlation and multiple
linear regression analyses. Results : Most participants were female (88%), and 48% reported
physician-diagnosed migraine. Mean migraine intensity was 7.44 ± 1.72. Migraine intensity was
positively correlated with migraine frequency (rs = 0.31, p p p p p p p = 0.005), perceived stress
(β = 0.23, p = 0.006), and aura (β = -0.19, p = 0.033) were significant predictors of migraine
intensity. Physical activity was not significantly associated with migraine intensity or frequency.
Conclusions : Migraine intensity was most consistently related to perceived stress and migraine
frequency, whereas migraine frequency was associated with dietary factors and BMI. Physical activity
was not associated with migraine outcomes. These findings suggest that lifestyle factors are related
to migraine characteristics, although the cross-sectional design does not allow conclusions about
causality.

MODEL SAYS: {'sample_size': 300, 'population': 'adults with migraine', 'method': 'correlational',
'includes_causal_claim': False}

====================================================================================================
ABS-002
A growing body of research has demonstrated the positive impact of nature-based interventions on
cognition, affect, and overall well-being. However, important questions remain regarding the
processes through which nature therapy exerts its effects. Participants (n = 188) were recruited and
randomly assigned to one of four experimental conditions (nature therapy, nature only, mindfulness
only, and control condition). While exposure to nature alone, mindfulness alone, and the combination
of the two significantly decreased negative mood, only the combination of nature and mindfulness
significantly improved positive mood. The present findings highlight the unique impact that nature-
based interventions that also incorporate mindfulness techniques have on positive mood. These
findings are consistent with research that demonstrates that positive mood enhancement is clinically
meaningful.

MODEL SAYS: {'sample_size': 188, 'population': 'participants', 'method': 'experimental',
'includes_causal_claim': True}

====================================================================================================
ABS-005
Introduction Stress remains a critical barrier to psychological wellbeing and academic functioning
among university students, particularly in cognitively demanding distance learning contexts. These
students often experience role conflict, social isolation, and increased mental load, which can
hinder effective learning. This study examined whether a targeted web-based mindfulness
intervention-focused on self-compassion and gratitude-produces more sustainable psychological
benefits than a comprehensive mindfulness program. Methods This randomized controlled trial included
167 university students who were randomized to one of two intervention arms; the final analytic
sample comprised 98 participants after pre-specified, arm-blind outlier handling and exclusions due
to missingness. Both interventions were delivered over 28 days using daily digital exercises.
Measures of mindfulness, self-compassion, and perceived stress were collected at baseline, post-
intervention, and at a three-month follow-up. Results Both intervention groups showed significant
short-term improvements in mindfulness and perceived stress ( p p Discussion The targeted program
was intentionally structured using cognitive learning theories-specifically Cognitive Load Theory to
reduce extraneous processing and Spaced Repetition Theory to support memory consolidation-by
emphasizing repetition of two core practices. The findings suggest that simplified, theory-informed
mindfulness interventions may improve psychological resilience in cognitively burdened learners by
facilitating deeper internalization and emotional regulation. This study contributes to educational
psychology by demonstrating how instructional design grounded in cognitive theory can enhance mental
health and support learners' capacity to manage stress in demanding academic contexts.

MODEL SAYS: {'sample_size': 98, 'population': 'university students', 'method': 'experimental',
'includes_causal_claim': True}

====================================================================================================
ABS-006
Introduction In today's world, where smartphones have become an indispensable part of life, the
existence of a department for treating smartphone addiction (nomophobia) in hospitals demonstrates
that this is a public health issue. Nomophobia symptoms are exhibited by individuals of almost all
ages, with young people being the least able to stay away from their phones. Against this backdrop,
the present study aims to investigate whether perceived physical activity barriers among students at
the Faculty of Sports Sciences have a predictive effect on their levels of nomophobia. Method A
total of 570 students enrolled in the Faculty of Sports Sciences participated in the study on a
voluntary basis. The Üsküdar Nomophobia Scale and the Perceived Physical Activity Barriers Scale
were employed. The data were analyzed using the Jamovi (2.3.28.0) statistical program with a 95%
confidence interval and a significance level of 0.05. Results A positive moderate correlation was
found between participants' nomophobia and physical activity barrier scores. The final regression
model was statistically significant [ R = 0.479, R 2 = 0.230, F (6,563) = 27.955, p R 2 = 0.213, p β
= 0.451, p p = 0.006) and teaching type ( p = 0.019) were also found to be significant predictors,
whereas BMI, gender and academic year were not. Conclusion The findings suggest that perceived
barriers to physical activity are a significant factor in predicting nomophobia among university
students. Reducing these barriers and promoting active lifestyles could encourage healthier
technology usage behaviors and reduce excessive smartphone addiction.

MODEL SAYS: {'sample_size': 570, 'population': 'university students at the Faculty of Sports
Sciences', 'method': 'correlational', 'includes_causal_claim': False}

====================================================================================================
ABS-023
Objective Increased screen exposure among adolescents leads to short- or long-term health problems.
This study aimed to examine the mediating role of screen exposure in the relationship between sleep
quality and healthy lifestyle among adolescents. Methods This cross-sectional and correlational
study was conducted between February and May 2025 in a province in the Black Sea region of Turkey
with 700 adolescents attending two high schools affiliated with the Provincial Directorate of
National Education. Data were collected using the Descriptive Characteristics Form, the Richard-
Campbell Sleep Questionnaire, the Adolescent Healthy Lifestyle Belief Scale, and the Screen Exposure
of Adolescents (ESEA) Scale. Descriptive, Pearson correlation, regression, and mediation analyses
were performed on the data. Results Participants' screen exposure levels and healthy lifestyle
beliefs were found to be moderate, while their sleep quality was good. Bootstrapping results
revealed that screen exposure in adolescents led to a decrease in sleep quality (β = -0.091; p
Conclusion It has been concluded that increased screen exposure affects sleep quality and beliefs
about healthy lifestyles in adolescents. To improve sleep quality and healthy lifestyle beliefs
among adolescents, it is necessary to reduce their screen exposure levels. Planning and implementing
nursing interventions for this purpose is extremely important in terms of protecting and improving
adolescent health.

MODEL SAYS: {'sample_size': 700, 'population': 'adolescents', 'method': 'correlational',
'includes_causal_claim': True}

### Discussion

Compare notes with the person next to you. Some places to look:

- **ABS-005**: the abstract reports that 167 students were randomized and that the final analytic sample was 98. What did the model report as `sample_size`? Which number should it be?
- **ABS-001**: a cross-sectional questionnaire study. Is that `correlational` or `other`? Also compare its `population` value with the text: were all 300 participants people with migraine?
- **ABS-002**: how informative is its `population` value? The abstract never describes who the 188 participants were. What should the model record in that case?
- **ABS-006**: the conclusion says perceived barriers to physical activity are "a significant factor in predicting nomophobia" and that reducing those barriers could reduce smartphone addiction. Is that a causal claim?
- **ABS-023**: the design is cross-sectional, but the abstract states that screen exposure "led to a decrease" in sleep quality and says it is "necessary to reduce" screen exposure. Did the model set `includes_causal_claim` to true? Should it?

What kind of changes do you think should we make to our prompting strategy to get better results?

## 7. Version 2: write the definitions down
We can try to add more rules (specifications) to our instructions, so the model doesn't make assumptions on our behalf. Including examples of what is or isn't part of a category can also help. Here's another try at prompting:

In [12]:
PROMPT_V2 = """Extract the following features from this research abstract.
Return a JSON object with exactly these keys:

- "sample_size": the total number of participants enrolled or recruited, as an integer.
  If the abstract reports both an initial and a final analytic sample, report the initial one.
  Use null if no number is stated.

- "population": a short phrase describing who the participants were, including any stated
  age group, occupation, or country (for example "university students in Italy").
  Use null if the participants are not described.

- "method": exactly one of:
  "experimental" = participants were randomly assigned to conditions that the researchers controlled;
  "correlational" = variables were measured but not manipulated, including surveys and
  cross-sectional questionnaire studies;
  "other" = anything else, such as reviews, meta-analyses, or qualitative studies.

- "includes_causal_claim": true if the conclusions state that one variable causes, increases,
  reduces, improves, leads to, or otherwise changes another, or recommend changing one variable
  in order to change another. Statements that only report an association, correlation, or link
  are false. The verb "predicts" by itself counts as association, not causation.
  Judge the claim that is made, not whether the study design justifies it.

Abstract:
{abstract}"""

df_v2 = run_batch(PROMPT_V2, subset)
df_v2

ABS-001 done
ABS-002 done
ABS-005 done
ABS-006 done
ABS-023 done

,sample_size,population,method,includes_causal_claim
abstract_id,,,,
ABS-001,300,adults in an online migraine-focused community,correlational,False
ABS-002,188,None,experimental,True
ABS-005,167,university students,experimental,True
ABS-006,570,university students at the Faculty of Sports S...,correlational,True
ABS-023,700,adolescents in a province in the Black Sea reg...,correlational,True

In [13]:
comparison = df_v1.join(df_v2, lsuffix="_v1", rsuffix="_v2")
comparison[["sample_size_v1", "sample_size_v2",
            "method_v1", "method_v2",
            "includes_causal_claim_v1", "includes_causal_claim_v2"]]

,sample_size_v1,sample_size_v2,method_v1,method_v2,includes_causal_claim_v1,includes_causal_claim_v2
abstract_id,,,,,,
ABS-001,300,300,correlational,correlational,False,False
ABS-002,188,188,experimental,experimental,True,True
ABS-005,98,167,experimental,experimental,True,True
ABS-006,570,570,correlational,correlational,False,True
ABS-023,700,700,correlational,correlational,True,True

Check which cells changed. What further changes might you make to the prompting strategy? What kind of errors might you be concerned about arising if we run this on the rest of the corpus?

## 8. Run the pipeline on the rest of the data.
Now, run the pipeline on all 30 abstracts in the corpus. Then, with the people around you, each pick a random (aim for non-overlapping) subset of results to manually inspect. What do you notice? Are there errors you're still seeing? What could be giving rise to those errors? Discuss your findings together.

In [14]:
# The full run takes about a minute for 30 abstracts.
df_full = run_batch(PROMPT_V2, abstracts)
df_full

ABS-001 done
ABS-002 done
ABS-003 done
ABS-004 done
ABS-005 done
ABS-006 done
ABS-007 done
ABS-008 done
ABS-009 done
ABS-010 done
ABS-011 done
ABS-012 done
ABS-013 done
ABS-014 done
ABS-015 done
ABS-016 done
ABS-017 done
ABS-018 done
ABS-019 done
ABS-020 done
ABS-021 done
ABS-022 done
ABS-023 done
ABS-024 done
ABS-025 done
ABS-026 done
ABS-027 done
ABS-028 done
ABS-029 done
ABS-030 done

,sample_size,population,method,includes_causal_claim
abstract_id,,,,
ABS-001,300,adults in an online migraine-focused community,correlational,False
ABS-002,188,None,experimental,True
ABS-003,125,medical students,correlational,False
ABS-004,201,students and teaching/non-teaching staff,correlational,True
ABS-005,167,university students,experimental,True
ABS-006,570,university students at the Faculty of Sports S...,correlational,True
ABS-007,138,None,experimental,True
ABS-008,209,office workers and bus drivers,experimental,True
ABS-009,161,university students,experimental,False
ABS-010,32,healthy young adult college students,experimental,True
ABS-011,168,young Chinese women aged 18-35 years,experimental,True
ABS-012,211,undergraduate health sciences students at Umm ...,correlational,True
ABS-013,153,adults aged 50 years and older,correlational,False
ABS-014,97,children in France,experimental,True
ABS-015,2192,university students in Italy,correlational,True
ABS-016,54653,Korean adolescents,correlational,True
ABS-017,478,young Saudi adults aged 18-25 years,correlational,True
ABS-018,362,None,experimental,True
ABS-019,1366,general population,correlational,True
ABS-020,2680,university students in China,correlational,True
ABS-021,52,adolescent boys aged 11-14 years from a rural ...,correlational,False
ABS-022,753,emotional labor workers,correlational,True
ABS-023,700,adolescents in a province in the Black Sea reg...,correlational,True
ABS-024,508,Chinese college students,correlational,True
ABS-025,70,adolescents aged 10-20 years,correlational,False
ABS-026,45,older adults aged ≥ 65 years,experimental,True
ABS-027,231,university students in Spain and Italy,correlational,False
ABS-028,689,job-seeking graduates in Bangladesh,correlational,True
ABS-029,1049,None,correlational,False
ABS-030,81,healthy adults,experimental,True

In [15]:
# Print a random sample of 5 results next to their abstracts.
# Re-run this cell to draw a different sample.
text_by_id = abstracts.set_index("abstract_id")["abstract"]

for abstract_id, coded in df_full.sample(5).iterrows():
    print("=" * 100)
    print(abstract_id)
    print(textwrap.fill(text_by_id[abstract_id], width=100))
    print()
    print(textwrap.fill(f"MODEL SAYS: {coded.to_dict()}", width=100))
    print()

====================================================================================================
ABS-021
Background Adolescence is a sensitive period for psychological, academic, and social development,
and sports participation has been described as a potential protective factor for academic
performance and psychological well-being. However, limited research has examined the combined
influence of sports involvement, sport type, and family background on adolescents' academic and
psychological outcomes. This study aimed to investigate the associations between organized sport
participation, sport type (football vs. judo), psychological well-being, psychosomatic symptoms,
academic performance, and family socioeconomic background among adolescent boys. Methods The sample
consisted of 52 boys aged 11-14 years from a rural school, divided into football players ( n = 13),
judo athletes ( n = 13), non-athletes ( n = 13), and a contextual subgroup of students with special
educational needs (SEN; n = 13), with the latter included for exploratory purposes only. Data
included school-record-based academic performance and validated self-report measures of life
satisfaction, depressive symptoms, psychosomatic complaints, perceived physical fitness, and
socioeconomic background. Results Athletes demonstrated significantly higher academic achievement
than non-athletes in overall grade point average ( p p p p = 0.03), and Hungarian ( p p p p p =
0.01), and fathers' occupational position ( p = 0.02) were significantly higher among athletes'
families. Perceived physical fitness was also rated higher by athletes ( p Conclusions Sport
participation was associated with more favorable academic and psychological indicators, yet also
with elevated depressive symptoms, highlighting the dual nature of organized sport during
adolescence. Future research should apply longitudinal designs, include female participants, and
incorporate objective indicators of training load.

MODEL SAYS: {'sample_size': 52, 'population': 'adolescent boys aged 11-14 years from a rural
school', 'method': 'correlational', 'includes_causal_claim': False}

====================================================================================================
ABS-013
Background and objectives Although previous studies suggest that social media may influence
individuals of different ages, comprehensive and objective research focusing on older adults remains
limited. This study aimed to investigate the associations between social media use on the well-being
of older adults using objective assessment methods. Methods A cross-sectional study was conducted
with 153 adults aged 50 years and older. Objective social media use was assessed through smartphone
screen-time records covering at least the previous 2 weeks, while participants also reported their
estimated daily usage durations. Psychological and nutritional well-being were evaluated using
validated scales: the De Jong Gierveld Loneliness Scale, PHQ-9 for depression, GAD-7 for anxiety,
and MNA-SF for nutritional status. Data were analyzed using nonparametric tests, correlation
analyses, and multivariable logistic regression. Results The mean age of participants was 64.2 years
(SD = 9.7), and 43.1% were female. The majority of participants (78.4%) had normal nutritional
status, but loneliness (53.6%), depression (62.7%), and anxiety (66.2%) were relatively high. The
median daily social media use was 90 min (IQR = 27-178). Older participants spent significantly less
time on social media ( p p p p > 0.05). Conclusions While higher income was associated with greater
use, social media engagement was not linked to adverse psychological or nutritional outcomes. These
findings suggest that social media use was not significantly associated with adverse psychological
or nutritional well-being among adults aged 50 years and older.

MODEL SAYS: {'sample_size': 153, 'population': 'adults aged 50 years and older', 'method':
'correlational', 'includes_causal_claim': False}

====================================================================================================
ABS-002
A growing body of research has demonstrated the positive impact of nature-based interventions on
cognition, affect, and overall well-being. However, important questions remain regarding the
processes through which nature therapy exerts its effects. Participants (n = 188) were recruited and
randomly assigned to one of four experimental conditions (nature therapy, nature only, mindfulness
only, and control condition). While exposure to nature alone, mindfulness alone, and the combination
of the two significantly decreased negative mood, only the combination of nature and mindfulness
significantly improved positive mood. The present findings highlight the unique impact that nature-
based interventions that also incorporate mindfulness techniques have on positive mood. These
findings are consistent with research that demonstrates that positive mood enhancement is clinically
meaningful.

MODEL SAYS: {'sample_size': 188, 'population': None, 'method': 'experimental',
'includes_causal_claim': True}

====================================================================================================
ABS-028
The purpose of this cross-sectional study was to determine the prevalence and factors associated
with depression and anxiety among job-seeking graduates in Bangladesh, as mental health issues are
often overlooked or stigmatized. The 689 participants were selected by means of convenience sampling
method. A self-reported questionnaire was used to gather data with sociodemographic data, lifestyle
characteristics, 7-item generalized anxiety disorder scale (GAD-7), and Patient Health
Questionnaire-9 (PHQ-9). It was established that 48.5% of the study population experienced
depression and anxiety at 39.3%. Approximately 86% of individuals who reported the presence of
depression and 87.8% of individuals who reported anxiety had finished studying back in the previous
2 years. Multivariable logistic regression models demonstrated that education level was found to be
significantly linked with depression (adjusted odds ratio [aOR] = 1.35; 95% confidence interval [CI]
= 0.908-2.022; p p p < 0.05). The study features the psychological vulnerability of job seekers in
Bangladesh, emphasizing the social need to recognize unemployment-related mental health challenges
and reduce stigma around seeking support. Findings call for integrating mental health support into
employment services and career programs. The study also lays groundwork for further research on
mental health interventions targeting unemployed youth. Lastly, the current article releases a
scarce perspective of the rates and causes of depression and anxiety in Bangladesh in the light of a
new timeframe.

MODEL SAYS: {'sample_size': 689, 'population': 'job-seeking graduates in Bangladesh', 'method':
'correlational', 'includes_causal_claim': True}

====================================================================================================
ABS-005
Introduction Stress remains a critical barrier to psychological wellbeing and academic functioning
among university students, particularly in cognitively demanding distance learning contexts. These
students often experience role conflict, social isolation, and increased mental load, which can
hinder effective learning. This study examined whether a targeted web-based mindfulness
intervention-focused on self-compassion and gratitude-produces more sustainable psychological
benefits than a comprehensive mindfulness program. Methods This randomized controlled trial included
167 university students who were randomized to one of two intervention arms; the final analytic
sample comprised 98 participants after pre-specified, arm-blind outlier handling and exclusions due
to missingness. Both interventions were delivered over 28 days using daily digital exercises.
Measures of mindfulness, self-compassion, and perceived stress were collected at baseline, post-
intervention, and at a three-month follow-up. Results Both intervention groups showed significant
short-term improvements in mindfulness and perceived stress ( p p Discussion The targeted program
was intentionally structured using cognitive learning theories-specifically Cognitive Load Theory to
reduce extraneous processing and Spaced Repetition Theory to support memory consolidation-by
emphasizing repetition of two core practices. The findings suggest that simplified, theory-informed
mindfulness interventions may improve psychological resilience in cognitively burdened learners by
facilitating deeper internalization and emotional regulation. This study contributes to educational
psychology by demonstrating how instructional design grounded in cognitive theory can enhance mental
health and support learners' capacity to manage stress in demanding academic contexts.

MODEL SAYS: {'sample_size': 167, 'population': 'university students', 'method': 'experimental',
'includes_causal_claim': True}

One question these features can answer: how often do studies whose designs can only measure associations state causal conclusions? Cross-tabulating `method` with `includes_causal_claim`:

In [16]:
pd.crosstab(df_full["method"], df_full["includes_causal_claim"])

includes_causal_claim  False  True
method
correlational              7     12
experimental               1     10

## 9. Discussion: should we publish this?

Suppose you wanted to report the table above as a finding about the health psychology literature. Are you confident enough in the pipeline to publish it? What evidence would satisfy you? What evidence would satisfy a skeptical reviewer?

Here are some practices that are recommended for evaluating LLM pipelines in industrial settings--so they won't all be applicable for every area of research. I highly recommend you look at the [Evals FAQ](https://hamel.dev/blog/posts/evals-faq/) from which these are drawn!

- **Read outputs until you stop finding new failure types.** Record every problem you see in your own words (the FAQ calls this open coding), group the notes into failure categories, and count them. Stop when new outputs stop adding categories; the FAQ suggests starting with about 100 outputs and stopping once 20 consecutive outputs add nothing new.
- **Build a hand-coded validation sample.** Code a random sample of abstracts yourself, before looking at the model's answers, then measure agreement.
- **Spot-check at scale.** Even after validation, sample and read outputs from every large run; a prompt tuned on one corpus can fail on abstracts from another field.